NAME = phonebook

CC = g++

FLAGS = -Wall -Wextra -Werror 

RM = rm -f

SRC = main.cpp ClassPhonebook.cpp phonebook.cpp

OBJ = $(SRC:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(FLAGS) $(OBJ) -o $@ 
	@echo "phonebook done."

%.o: %.c
	$(CC) $(FLAGS) -o $@ -c $<

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean all
